//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grabacr07.KanColleViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37564")]
        public int LocalProxyPort {
            get {
                return ((int)(this["LocalProxyPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.dmm.com/netgame/social/application/-/detail/=/app_id=854854/")]
        public global::System.Uri KanColleUrl {
            get {
                return ((global::System.Uri)(this["KanColleUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("333")]
        public double UIContentHight {
            get {
                return ((double)(this["UIContentHight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000")]
        public int FeatureBrowserEmulation {
            get {
                return ((int)(this["FeatureBrowserEmulation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/KCV-Localisation/KanColleViewer-Translations/ma" +
            "ster/")]
        public global::System.Uri XMLTransUrl {
            get {
                return ((global::System.Uri)(this["XMLTransUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://kcv.koumakan.jp/version/")]
        public global::System.Uri KCVUpdateUrl {
            get {
                return ((global::System.Uri)(this["KCVUpdateUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("var flashQuality = function () {{\n    for (var objs = document.embeds, i = objs.l" +
            "ength - 1; i >= 0; i--) {{\n        \t\t\n        var embedElem = document.createEle" +
            "ment(\'embed\');\n        var parentElem = objs[i].parentNode;\n        embedElem.se" +
            "tAttribute(\'quality\', \'{0}\');\n        embedElem.setAttribute(\'wmode\', \'{1}\');\n  " +
            "      embedElem.setAttribute(\'type\', \'application/x-shockwave-flash\');\n        e" +
            "mbedElem.setAttribute(\'id\', objs[i].getAttribute(\'id\'));\n        embedElem.setAt" +
            "tribute(\'width\', objs[i].getAttribute(\'width\'));\n        embedElem.setAttribute(" +
            "\'height\', objs[i].getAttribute(\'height\'));\n        embedElem.setAttribute(\'src\'," +
            " objs[i].getAttribute(\'src\'));\n        embedElem.setAttribute(\'bgcolor\', objs[i]" +
            ".getAttribute(\'bgcolor\'));\n        embedElem.setAttribute(\'allowScriptAccess\', o" +
            "bjs[i].getAttribute(\'allowScriptAccess\'));\n        embedElem.setAttribute(\'base\'" +
            ", objs[i].getAttribute(\'base\'));\n        parentElem.removeChild(objs[i]);\n      " +
            "  parentElem.appendChild(embedElem);\n    }}\n    \n    for (objs = document.getEle" +
            "mentsByTagName(\'object\'), i = objs.length - 1; i >= 0; i--) {{\n        var embed" +
            "Elem = document.createElement(\'embed\');\n        var parentElem = objs[i].parentN" +
            "ode;\n        embedElem.setAttribute(\'quality\', \'{0}\');\n        embedElem.setAttr" +
            "ibute(\'wmode\', \'{1}\');\n        embedElem.setAttribute(\'id\', objs[i].getAttribute" +
            "(\'id\'));\n        embedElem.setAttribute(\'type\', \'application/x-shockwave-flash\')" +
            "; \n        embedElem.setAttribute(\'width\', objs[i].getAttribute(\'width\'));\n     " +
            "   embedElem.setAttribute(\'height\', objs[i].getAttribute(\'height\'));       \n    " +
            "    \n        for (var c = objs[i].childNodes, j = c.length - 1, set = false; j >" +
            "= 0; j--) {{\n            if ((c[j].tagName == \'PARAM\') && (c[j].getAttribute(\'na" +
            "me\').toLowerCase() == \'src\'))\n                embedElem.setAttribute(\'src\', c[j]" +
            ".getAttribute(\'value\'));\n            else if ((c[j].tagName == \'PARAM\') && (c[j]" +
            ".getAttribute(\'name\').toLowerCase() == \'movie\'))\n                embedElem.setAt" +
            "tribute(\'src\', c[j].getAttribute(\'value\'));\n            else if ((c[j].tagName =" +
            "= \'PARAM\') && (c[j].getAttribute(\'name\').toLowerCase() == \'bgcolor\'))\n          " +
            "      embedElem.setAttribute(\'bgcolor\', c[j].getAttribute(\'value\'));\n           " +
            " else if ((c[j].tagName == \'PARAM\') && (c[j].getAttribute(\'name\').toLowerCase() " +
            "== \'allowscriptaccess\'))\n                embedElem.setAttribute(\'allowScriptAcce" +
            "ss\', c[j].getAttribute(\'value\'));\n            else if ((c[j].tagName == \'PARAM\')" +
            " && (c[j].getAttribute(\'name\').toLowerCase() == \'base\'))\n                embedEl" +
            "em.setAttribute(\'base\', c[j].getAttribute(\'value\'));\n        }}\n        \n       " +
            " parentElem.removeChild(objs[i]);\n        parentElem.appendChild(embedElem);\n   " +
            " }}\n}};\n\nvar TimedInject = setInterval(function () {{\n    CheckChange();\n}}, 100" +
            ");\n\nfunction CheckChange() {{\n    if (document.getElementById(\'flashWrap\').inner" +
            "HTML.length > 10) {{\n        flashQuality();\n        clearInterval(TimedInject);" +
            "\n    }}\n    else if (!document.getElementById(\'flashWrap\'))\n        clearInterva" +
            "l(TimedInject);\n}}")]
        public string FlashQualityJS {
            get {
                return ((string)(this["FlashQualityJS"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<embed id=\"KCVGenerated\" width=\"800\" height=\"480\" wmode=\"{1}\" quality=\"{0}\" bgcol" +
            "or=\"#000\" allowScriptAccess=\"always\" type=\"application/x-shockwave-flash\" src=\"{" +
            "2}\">")]
        public string FlashEmbed {
            get {
                return ((string)(this["FlashEmbed"]));
            }
            set {
                this["FlashEmbed"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"body {
    margin:0;
    overflow:hidden;
}

#game_frame {
    position:fixed;
    left:50%;
    top:-16px;
    margin-left:-450px;
    z-index:1;
}

#flashWrap {
    position:free;
    z-index:1;
    margin:0;
}

#spacing_top, #sectionWrap {
    visibility: hidden !important;
    height:0 !important;
    display: none !important;
}")]
        public string OverrideStyleSheet {
            get {
                return ((string)(this["OverrideStyleSheet"]));
            }
        }
    }
}
